/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

/**
 * Alert result data in JSON format
 */
export type AlertResult = { [key: string]: unknown };
