/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type AlertUserAlertType =
  (typeof AlertUserAlertType)[keyof typeof AlertUserAlertType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertUserAlertType = {
  PROPERTY: "PROPERTY",
} as const;
