/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { User } from "./user";

export interface Attachment {
  userFrom?: User;
  userTo?: User;
  fileId?: string;
  uploadUrl?: string;
  downloadUrl?: string;
  originalName?: string;
}
