/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export interface Brokerage {
  id?: number;
  name?: string;
  enabled?: boolean;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
}
