/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type ChangePublicationStatus2Body =
  (typeof ChangePublicationStatus2Body)[keyof typeof ChangePublicationStatus2Body];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangePublicationStatus2Body = {
  DRAFT: "DRAFT",
  PASSWORD_PROTECTED: "PASSWORD_PROTECTED",
  PUBLISHED: "PUBLISHED",
} as const;
