/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type CheckoutSessionDtoStatus =
  (typeof CheckoutSessionDtoStatus)[keyof typeof CheckoutSessionDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckoutSessionDtoStatus = {
  IN_PROCESS: "IN_PROCESS",
  SUCCESS: "SUCCESS",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
} as const;
