/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type ConversationSummaryChatAllowanceType =
  (typeof ConversationSummaryChatAllowanceType)[keyof typeof ConversationSummaryChatAllowanceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationSummaryChatAllowanceType = {
  REJECTED: "REJECTED",
  ACCEPTED: "ACCEPTED",
  PENDING: "PENDING",
  BLOCKED: "BLOCKED",
  SILENCED: "SILENCED",
} as const;
