/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { Currency } from "./currency";

/**
 * Country information
 */
export interface Country {
  /** Country identifier */
  id: number;
  /** Country code (ISO 3166 alpha-2) */
  code?: string;
  /** Country name */
  name?: string;
  /** Language code */
  lang?: string;
  currency?: Currency;
  /** Locale code */
  locale?: string;
}
