/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type DropdownOptionGroupTranslationManagement =
  (typeof DropdownOptionGroupTranslationManagement)[keyof typeof DropdownOptionGroupTranslationManagement];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DropdownOptionGroupTranslationManagement = {
  TOTAL: "TOTAL",
  PARTIAL: "PARTIAL",
  NONE: "NONE",
} as const;
