/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { DropdownOptionParentInfo } from "./dropdownOptionParentInfo";

export interface DropdownOption {
  optionId?: number;
  name?: string;
  data1?: string;
  data2?: string;
  data3?: string;
  data4?: string;
  data5?: string;
  data6?: string;
  data7?: string;
  data8?: string;
  dependsOnLang?: boolean;
  parentInfo?: DropdownOptionParentInfo;
}
