/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type FavoriteResourceType =
  (typeof FavoriteResourceType)[keyof typeof FavoriteResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FavoriteResourceType = {
  PROPERTY: "PROPERTY",
} as const;
