/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

/**
 * Resource data in JSON format
 */
export type FavoriteResource = { [key: string]: unknown };
