/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type FilterShowingStepSequenceAfter =
  (typeof FilterShowingStepSequenceAfter)[keyof typeof FilterShowingStepSequenceAfter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterShowingStepSequenceAfter = {
  INIT_GROUP: "INIT_GROUP",
  END_GROUP: "END_GROUP",
  AND: "AND",
  OR: "OR",
} as const;
