/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type FindProperty1Params = {
  /**
   * Password for protected properties
   */
  password?: string;
};
