/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { LocalDateTimeQueryString } from "./localDateTimeQueryString";

export type GetConversation1Params = {
  /**
   * User A Id
   */
  userAId?: number;
  /**
   * User B Id
   */
  userBId?: number;
  /**
   * limit results
   */
  limit?: number;
  /**
   * return results before date time
   */
  before_datetime?: LocalDateTimeQueryString;
};
