/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type GetGroupMembers1Params = {
  /**
   * Starting page index (zero-based)
   */
  pageFrom?: number;
  /**
   * Ending page index (zero-based)
   */
  pageTo?: number;
};
