/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type GetGeoLocationsByLatLng1Params = {
  /**
   * Comma-separated latitude and longitude coordinates
   */
  latlng?: string;
  /**
   * Text representation of an address to geocode
   */
  address?: string;
  /**
   * ISO country code to restrict the address search
   */
  countryCode?: string;
  /**
   * Text to use for location auto-completion suggestions
   */
  autoCompleteText?: string;
  /**
   * Search radius in meters for location suggestions (used with latlng and autoCompleteText)
   */
  radius?: number;
};
