/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type GetRecentProperties1Params = {
  /**
   * Email to filter properties by user
   */
  email?: string;
  /**
   * Minutes to look back (default 60)
   */
  minutes?: number;
};
