/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type GroupGroupStatus =
  (typeof GroupGroupStatus)[keyof typeof GroupGroupStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupGroupStatus = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
} as const;
