/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { User } from "./user";
import type { Group } from "./group";
import type { GroupMemberGroupMemberStatus } from "./groupMemberGroupMemberStatus";

export interface GroupMember {
  id?: number;
  user?: User;
  group?: Group;
  creationDate?: string;
  groupMemberStatus?: GroupMemberGroupMemberStatus;
}
