/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type GroupMemberGroupMemberStatus =
  (typeof GroupMemberGroupMemberStatus)[keyof typeof GroupMemberGroupMemberStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupMemberGroupMemberStatus = {
  INVITED: "INVITED",
  REQUESTED: "REQUESTED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  REMOVED: "REMOVED",
  LEFT: "LEFT",
} as const;
