/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterTypeEntryRangeFieldPresentation =
  (typeof HcFilterTypeEntryRangeFieldPresentation)[keyof typeof HcFilterTypeEntryRangeFieldPresentation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterTypeEntryRangeFieldPresentation = {
  INTEGER: "INTEGER",
  DOUBLE: "DOUBLE",
  CURRENCY: "CURRENCY",
  DATE: "DATE",
} as const;
