/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { HcFilterTypeFilterTypeNature } from "./hcFilterTypeFilterTypeNature";
import type { HcFilterTypeRangeFieldPresentation } from "./hcFilterTypeRangeFieldPresentation";

export interface HcFilterType {
  id?: number;
  name?: string;
  filterTypeNature?: HcFilterTypeFilterTypeNature;
  useSlider?: boolean;
  validateMin?: boolean;
  validateMax?: boolean;
  allowMultiple?: boolean;
  useSearch?: boolean;
  useSort?: boolean;
  useSelectAll?: boolean;
  useRemoteList?: boolean;
  useLinks?: boolean;
  useYesNoDropdown?: boolean;
  useCheckbox?: boolean;
  useRadio?: boolean;
  useText?: boolean;
  toggle?: boolean;
  sortSign?: boolean;
  rangeOnlyFrom?: boolean;
  rangeOnlyTo?: boolean;
  rangeFieldPresentation?: HcFilterTypeRangeFieldPresentation;
}
