/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterFilterWorkerOption =
  (typeof HcFilterFilterWorkerOption)[keyof typeof HcFilterFilterWorkerOption];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterFilterWorkerOption = {
  PROPERTY_LOCATION_KEY: "PROPERTY_LOCATION_KEY",
  COUNTRY_KEY: "COUNTRY_KEY",
  PROPERTY_PROPOSAL_KEY: "PROPERTY_PROPOSAL_KEY",
  RANGE: "RANGE",
  DROPDOWN: "DROPDOWN",
  BOOLEAN: "BOOLEAN",
  CURRENCY_RANGE: "CURRENCY_RANGE",
  ROI: "ROI",
  FREE_TEXT: "FREE_TEXT",
  ID: "ID",
  PUBLICATION_STATE: "PUBLICATION_STATE",
  PUBLICATION_DATE: "PUBLICATION_DATE",
  GEOLOCATION_AREA: "GEOLOCATION_AREA",
  GROUPS: "GROUPS",
  USER_ID: "USER_ID",
  XML_ID: "XML_ID",
} as const;
