/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterTypeFilterTypeNature =
  (typeof HcFilterTypeFilterTypeNature)[keyof typeof HcFilterTypeFilterTypeNature];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterTypeFilterTypeNature = {
  DROPDOWN: "DROPDOWN",
  YESNO: "YESNO",
  RANGE: "RANGE",
  TEXT: "TEXT",
  AREA_RANGE: "AREA_RANGE",
} as const;
