/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterHcListerOption =
  (typeof HcFilterHcListerOption)[keyof typeof HcFilterHcListerOption];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterHcListerOption = {
  PROPERTY_TYPE: "PROPERTY_TYPE",
} as const;
