/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterTypeRangeFieldPresentation =
  (typeof HcFilterTypeRangeFieldPresentation)[keyof typeof HcFilterTypeRangeFieldPresentation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterTypeRangeFieldPresentation = {
  INTEGER: "INTEGER",
  DOUBLE: "DOUBLE",
  CURRENCY: "CURRENCY",
  DATE: "DATE",
} as const;
