/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterChoice =
  (typeof HcFilterChoice)[keyof typeof HcFilterChoice];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterChoice = {
  SHOW: "SHOW",
  HIDE: "HIDE",
} as const;
