/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type HcFilterConditionMinOperand =
  (typeof HcFilterConditionMinOperand)[keyof typeof HcFilterConditionMinOperand];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HcFilterConditionMinOperand = {
  GT: "GT",
  GET: "GET",
  EQ: "EQ",
  LT: "LT",
  LET: "LET",
} as const;
