/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { HcFilterConditionMinOperand } from "./hcFilterConditionMinOperand";
import type { HcFilterConditionMaxOperand } from "./hcFilterConditionMaxOperand";

export interface HcFilterCondition {
  filterId?: number;
  searchSpecific?: boolean;
  containsAtLeastOne?: boolean;
  containsAll?: boolean;
  containsNumber?: boolean;
  number?: number;
  selectedNumberAny?: number;
  minOperand?: HcFilterConditionMinOperand;
  maxOperand?: HcFilterConditionMaxOperand;
  minValue?: number;
  maxValue?: number;
  applyMinConstraint?: boolean;
  applyMaxConstraint?: boolean;
  apply?: boolean;
}
