/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export interface LocaleSet {
  pnemonic?: string;
  description?: string;
  enUS?: string;
  esES?: string;
  deDE?: string;
  zhCN?: string;
  ruRU?: string;
  frFR?: string;
  ptPT?: string;
  itIT?: string;
  jaJP?: string;
}
