/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
  TO_BROKER__ALERT_CREATED: "TO_BROKER__ALERT_CREATED",
  TO_USER__WEEKLY_PROPERTIES: "TO_USER__WEEKLY_PROPERTIES",
  TO_USER__WEEKLY_PAYED_SUBSCRIBERS: "TO_USER__WEEKLY_PAYED_SUBSCRIBERS",
  TO_USER__CUSTOMIZED_ALERT: "TO_USER__CUSTOMIZED_ALERT",
  TO_USER__WEEKLY_GROUP_PROPERTIES: "TO_USER__WEEKLY_GROUP_PROPERTIES",
  TO_USER__NEWSLETTER_NEW_SUBSCRIBER: "TO_USER__NEWSLETTER_NEW_SUBSCRIBER",
  TO_USER__NEWSLETTER_CONFIRMATION: "TO_USER__NEWSLETTER_CONFIRMATION",
  TO_USER__NEWSLETTER_LISTING: "TO_USER__NEWSLETTER_LISTING",
} as const;
