/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

/**
 * Token used for password recovery process
 */
export interface PasswordRecoveryToken {
  /** Unique identifier for the token */
  id?: number;
  /** ID of the associated user */
  idAssociated?: number;
  /** Token content that is sent in the recovery email */
  tokenContent: string;
  /** Expiration date of the token */
  dueDate?: string;
  /** Whether the token is active or already used */
  active?: boolean;
  /** Date when the token was created */
  expeditionDate?: string;
}
