/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export interface PropertyFieldValueSpec {
  /**
   * @minLength 0
   * @maxLength 5000
   */
  strVal?: string;
  boolVal?: boolean;
  dateVal?: string;
  doubleVal?: number;
  intVal?: number;
  bigIntVal?: number;
}
