/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { PropertyFieldValueSpec } from "./propertyFieldValueSpec";

export interface PropertyFieldValue {
  bdid?: number;
  identifier?: number;
  text?: PropertyFieldValueSpec;
  data1?: PropertyFieldValueSpec;
  data2?: PropertyFieldValueSpec;
  data3?: PropertyFieldValueSpec;
}
