/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type PropertyPublicationState =
  (typeof PropertyPublicationState)[keyof typeof PropertyPublicationState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyPublicationState = {
  AVAILABLE: "AVAILABLE",
  RENTED: "RENTED",
  SOLD: "SOLD",
  DRAFT: "DRAFT",
} as const;
