/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { PropertyFilterEntry } from "./propertyFilterEntry";
import type { CurrencyAmmount } from "./currencyAmmount";
import type { DropdownOption } from "./dropdownOption";

export interface PropertyFilterSubmission {
  apply?: boolean;
  propertyFilter: PropertyFilterEntry;
  minValue?: number;
  maxValue?: number;
  minDateValue?: string;
  maxDateValue?: string;
  minCrcyValue?: CurrencyAmmount;
  maxCrcyValue?: CurrencyAmmount;
  minLocalDateTimeValue?: string;
  maxLocalDateTimeValue?: string;
  latitudeValue?: number;
  longitudeValue?: number;
  radiusValue?: number;
  userId?: number;
  xmlId?: string;
  freeText?: string;
  selectedFilterOptions?: DropdownOption[];
}
