/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type PropertyFieldData1Type =
  (typeof PropertyFieldData1Type)[keyof typeof PropertyFieldData1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyFieldData1Type = {
  SAME: "SAME",
  INT: "INT",
  DOUBLE: "DOUBLE",
  BOOLEAN: "BOOLEAN",
  TEXT: "TEXT",
  DATE: "DATE",
  DATETIME: "DATETIME",
  FILE: "FILE",
  BIGINT: "BIGINT",
} as const;
