/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type RetrieveChatUserStatus1200 =
  (typeof RetrieveChatUserStatus1200)[keyof typeof RetrieveChatUserStatus1200];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RetrieveChatUserStatus1200 = {
  OFFLINE: "OFFLINE",
  ONLINE: "ONLINE",
} as const;
