/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { Language } from "./language";
import type { CountryTelephonePrefix } from "./countryTelephonePrefix";
import type { UserType } from "./userType";
import type { UserLanguage } from "./userLanguage";
import type { UserDescription } from "./userDescription";
import type { Country } from "./country";
import type { GeoPlace } from "./geoPlace";
import type { GooglePlaceReview } from "./googlePlaceReview";
import type { UserSkill } from "./userSkill";
import type { Brokerage } from "./brokerage";

export interface SkilledUser {
  language?: Language;
  /**
   * @minLength 0
   * @maxLength 160
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 45
   */
  firstName?: string;
  /**
   * @minLength 0
   * @maxLength 45
   */
  lastName?: string;
  id?: number;
  password?: string;
  confirmedFlag?: boolean;
  registerDate?: string;
  /**
   * @minLength 0
   * @maxLength 80
   */
  webSite?: string;
  /**
   * @minLength 0
   * @maxLength 160
   */
  linkedIn?: string;
  /**
   * @minLength 0
   * @maxLength 45
   */
  skype?: string;
  base64Image?: string;
  imageLink?: string;
  mainSpokenLanguage?: Language;
  telephonePrefix?: CountryTelephonePrefix;
  telephoneNumber?: string;
  userTypes?: UserType[];
  userLanguages?: UserLanguage[];
  userDescriptions?: UserDescription[];
  country?: Country;
  role?: string;
  backgroundImageBase64?: string;
  backgroundImageLink?: string;
  profileName?: string;
  lastActivity?: string;
  chatStatus?: string;
  chatsCount?: number;
  phoneVerified?: boolean;
  geoPlace?: GeoPlace;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  chamberOfCommerceUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  facebookUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  instagramUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  twitterUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  wechatUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  vkUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  videoUrl?: string;
  /** @pattern https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*) */
  bookAnAppointmentUrl?: string;
  googlePlaceId?: string;
  googlePlaceReviews?: GooglePlaceReview[];
  achievementsYearsOfExperience?: number;
  achievementsDealsClosed?: number;
  achievementsPercentageOfAllAgents?: number;
  achievementsGooglePlaceId?: string;
  focusOnCommercial?: boolean;
  focusOnResidential?: boolean;
  focusOnRental?: boolean;
  focusOnSelling?: boolean;
  imprintTitle?: string;
  imprintDescription?: string;
  imprintBase64Image?: string;
  imprintLogoLink?: string;
  showEmailInProfile?: boolean;
  showEmailInProperty?: boolean;
  showPhoneInProperty?: boolean;
  isAllowSaveContact?: boolean;
  city?: string;
  referral?: string;
  skills?: UserSkill[];
  subscriptionPlanName?: string;
  brokerage?: Brokerage;
  groupMemberStatus?: string;
  imprintImageLink?: string;
}
