/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

/**
 * Previous attributes of the object before the event
 */
export type StripeEventDataPreviousAttributes = { [key: string]: unknown };
