/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { Address } from "./address";

export interface SubscribedUser {
  id?: number;
  email?: string;
  firstName?: string;
  lastName?: string;
  paymentAppId?: string;
  address?: Address;
  created?: string;
}
