/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { SubscriptionPriceDtoRenewalType } from "./subscriptionPriceDtoRenewalType";

export interface SubscriptionPriceDto {
  id: string;
  price?: number;
  currency?: string;
  renewalType?: SubscriptionPriceDtoRenewalType;
}
