/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type UpdateGroupMembershipStatus1Status =
  (typeof UpdateGroupMembershipStatus1Status)[keyof typeof UpdateGroupMembershipStatus1Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateGroupMembershipStatus1Status = {
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  REMOVED: "REMOVED",
} as const;
