/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type UserSubscriptionDtoStatus =
  (typeof UserSubscriptionDtoStatus)[keyof typeof UserSubscriptionDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSubscriptionDtoStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;
