/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

export type UserSubscriptionDtoRenewalType =
  (typeof UserSubscriptionDtoRenewalType)[keyof typeof UserSubscriptionDtoRenewalType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSubscriptionDtoRenewalType = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  EVERY_3_MONTHS: "EVERY_3_MONTHS",
  EVERY_6_MONTHS: "EVERY_6_MONTHS",
  YEARLY: "YEARLY",
} as const;
