/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */
import type { SkilledUser } from "./skilledUser";

export interface UserFilterResult {
  count?: number;
  userList?: SkilledUser[];
}
