/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hallocasa API
 * Hallocasa API Documentation
 * OpenAPI spec version: v1
 */

/**
 * Result specification for pagination and sorting of user search results
 */
export interface UserFilterResultSpec {
  pageFrom?: number;
  pageTo?: number;
  orderByMostRecent?: boolean;
  orderByLessRecent?: boolean;
  asc?: boolean;
  loadCount?: boolean;
  orderBy?: string[];
  /** Sort users by most recent login first */
  orderByMostRecentLogin?: boolean;
  /** Sort users by least recent login first */
  orderByLessRecentLogin?: boolean;
}
